#!/bin/bash

set -x -e

version=`cat mapfs-version/number`
pushd mapfs-release

bosh -n create-release --tarball=dev_releases/mapfs/mapfs-$version.tgz --version $version --name mapfs --force
mv dev_releases/mapfs/mapfs-$version.tgz ../created-plugins-release/mapfs-$version.tgz
popd
